config/routes.rb
Teambox::Application.routes.draw do

  # If secure_logins is true, constrain matches to ssl requests
  class SSLConstraints
    def self.matches?(request)
      !Teambox.config.secure_logins || request.ssl?
    end
  end

  resources :sites, :only => [:show, :new, :create]

  match '/public' => 'public/projects#index', :as => :public_projects
  match '/goodbye' => 'static_pages#goodbye', :as => :goodbye 

  namespace :public do
    match ':id' => 'projects#show', :as => :project
    match ':project_id/conversations' => 'conversations#index', :as => :project_conversations
    match ':project_id/conversations/:id' => 'conversations#show', :as => :project_conversation
    match ':project_id/:id' => 'pages#show', :as => :project_page
  end

  match 'api' => 'apidocs#index', :as => :api
  match 'api/concepts' => 'apidocs#concepts', :as => :api_concepts
  match 'api/routes' => 'apidocs#routes', :as => :api_routes
  match 'api/auth' => 'apidocs#auth', :as => :api_auth
  match 'api/changes' => 'apidocs#changes', :as => :api_changes
  match 'api/:model' => 'apidocs#model', :as => :api_model

  resources :sprockets, :only => [:index, :show]

  #Constrain all requests to the ssl constraint
  scope :constraints => SSLConstraints do

    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/login/:username' => 'sessions#backdoor', :as => :login_backdoor if Rails.env.cucumber?

    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup

    match '/search' => 'search#index', :as => :search

    match '/guides' => 'guides#index', :as => :guides

    match '/text_styles' => 'users#text_styles', :as => :text_styles
    match '/email_posts_path' => 'users#email_posts', :as => :email_posts
    match '/invite_format' => 'invitations#invite_format', :as => :invite_format
    match '/feeds' => 'users#feeds', :as => :feeds
    match '/calendars' => 'users#calendars', :as => :calendars
    match '/disable_splash' => 'users#disable_splash', :as => :disable_splash
    match '/forgot' => 'reset_passwords#new', :as => :forgot_password
    match '/reset/:reset_code' => 'reset_passwords#reset', :as => :reset_password
    match '/forgetting' => 'reset_passwords#update_after_forgetting', :as => :update_after_forgetting, :method => :put
    match '/reset_password_sent' => 'reset_passwords#sent', :as => :sent_password

    match '/format/:f' => 'sessions#change_format', :as => :change_format

    match '/projects/:project_id/invite/:login' => 'invitations#create', :as => :create_project_invitation, :method => :post

    match '/auth/:provider/callback' => 'auth#callback', :as => :auth_callback
    match '/auth/failure' => 'auth#failure', :as => :auth_failure
    match '/complete_signup' => 'users#complete_signup', :as => :complete_signup
    match '/auth/:provider/unlink' => 'users#unlink_app', :as => :unlink_app

    resources :google_docs do
      get :search, :on => :collection
    end
    
    resources :google_calendars

    #RAILS 3 Useless resource?
    resources :reset_passwords
    resource :session

    resources :organizations do
      member do
        get :projects
        get :external_view
        get :delete
        get :appearance
        put :update_appearance
      end
      resources :memberships do
        member do
          get :change_role
          get :add
          get :remove
        end
      end
      resources :task_list_templates do
        collection do
          put :reorder
        end
      end
    end

    match '/account/settings' => 'users#edit', :as => :account_settings, :sub_action => 'settings'
    match '/account/picture' => 'users#edit', :as => :account_picture, :sub_action => 'picture'
    match '/account/profile' => 'users#edit', :as => :account_profile, :sub_action => 'profile'
    match '/account/linked_accounts' => 'users#edit', :as => :account_linked_accounts, :sub_action => 'linked_accounts'
    match '/account/notifications' => 'users#edit', :as => :account_notifications, :sub_action => 'notifications'
    match '/account/delete' => 'users#edit', :as => :account_delete, :sub_action => 'delete'
    match '/account/destroy' => 'users#destroy', :as => :destroy_user
    match '/account/activity_feed_mode/collapsed' => 'users#change_activities_mode', :as => :collapse_activities, :collapsed => true
    match '/account/activity_feed_mode/expanded' => 'users#change_activities_mode', :as => :expand_activities, :collapsed => false
    match '/account/watch_list' => 'watchers#index', :as => :watch_list
    post  '/account/watch_list/unwatch/:watch_id' => 'watchers#unwatch', :as => :unwatch
    post  '/account/stats/:stat/inc' => 'users#increment_stat'
    post  '/account/badge/:badge/grant' => 'users#grant_badge'
    post  '/account/first_steps/hide' => 'users#hide_first_steps'

    resources :teambox_datas, :path => '/datas' do
      member do
        get :download
      end
    end

    resources :users do
      resources :invitations
      member do
        get :confirm_email
        get :unconfirmed_email
        get :contact_importer
      end
      resources :conversations
      resources :task_lists do
        resources :tasks
      end
      match 'activities/users/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    end

    match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
    match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    match 'activities/:id/show_thread(.:format)' => 'activities#show_thread', :as => :show_thread, :method => :get

    match 'projects/archived.:format' => 'projects#index', :as => :project_archived, :sub_action => 'archived'

    match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

    resources :projects do
      member do
        post :accept
        post :decline
        get :join
      end

      match 'time/:year/:month' => 'hours#index', :as => :hours_by_month, :via => :get
      match 'time/by_period' => 'hours#by_period', :as => :hours_by_period, :via => :get
      match 'time' => 'hours#index', :as => :time
      match 'settings' => 'projects#edit', :as => :settings, :sub_action => 'settings'
      match 'picture' => 'projects#edit', :as => :picture, :sub_action => 'picture'
      match 'deletion' => 'projects#edit', :as => :deletion, :sub_action => 'deletion'
      match 'ownership' => 'projects#edit', :as => :ownership, :sub_action => 'ownership'

      resources :invitations do
        member do
          put :accept
          put :decline
          get :resend
        end
      end

      match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
      match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get

      match 'move/:id' => 'uploads#move', :via => :put, :as => :move_resource

      resources :uploads do
        member do
          get :public_download
          put :rename
        end
        collection do
          resources :folders, :except => [:show, :index, :new] do
            member do
              get :public_download, :controller => 'uploads', :action => 'public_download'
              put :rename
            end
          end
        end
      end

      match 'downloadable/:id/email_public' => "uploads#email_public", :via => :post, :as => :email_public_download
      
      match 'uploads/folders/:id' => 'uploads#index', :via => :get
      match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

      match 'invite_people' => 'projects#invite_people', :as => :invite_people, :via => :get
      match 'invite_people' => 'projects#send_invites', :as => :send_invites, :via => :post

      resources :tasks do
        member do
          put :reorder
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :task_lists do
        collection do
          get :gantt_view
          get :archived
          put :reorder
        end
        member do
          put :archive
          put :unarchive
          put :watch
          put :unwatch
        end

        resources :tasks do
          member do
            put :watch
            put :unwatch
          end

          resources :comments
        end
      end

      match 'contacts' => 'people#contacts', :as => :contacts, :method => :get

      resources :people do
        member do
          get :destroy
        end
      end

      resources :conversations do
        member do
          put :convert_to_task
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :pages do
        collection do
          post :resort
        end
        member do
          post :reorder
          put :watch
          put :unwatch
        end
        # In rails 2, we have :pages, :has_many => :task_list ?!
        resources :notes,:dividers,:uploads
      end

      match 'search' => 'search#index', :as => :search

      resources :google_docs do
        collection do
          :search
        end
        member do
          put :write_access, :path => "write_access/:access", :access => /lock|unlock/
        end
      end
    end

    namespace :api_v1, :path => 'api/1' do
      resources :app_links, :except => [ :edit, :update ]
      resources :projects, :except => [:new, :edit] do

        resources :activities, :only => [:index, :show]

        resources :people, :except => [:create, :new, :edit]

        resources :comments, :except => [:new, :create, :edit]

        resources :conversations, :except => [:new, :edit] do
          member do
            put :watch
            put :unwatch
            post :convert_to_task
          end

          resources :comments, :except => [:new, :edit]
        end

app/models/teambox_data/attributes.rb
class TeamboxData
  attr_accessor :data
  attr_accessor :import_data
  
  serialize :project_ids
  serialize :processed_objects
  serialize :user_map

  TYPE_LOOKUP = {:import => 0, :export => 1}
  TYPE_CODES = TYPE_LOOKUP.invert

  IMPORT_STATUS_NAMES = [:uploading, :mapping, :pre_processing, :processing, :imported]
  IMPORT_STATUSES = IMPORT_STATUS_NAMES.each_with_index.each_with_object({}) {|(name, code), all| all[name] = code }

  EXPORT_STATUS_NAMES = [:selecting, :pre_processing, :processing, :exported]
  EXPORT_STATUSES = EXPORT_STATUS_NAMES.each_with_index.each_with_object({}) {|(name, code), all| all[name] = code }

  def user_map
    if self[:user_map].nil?
      known_map = {}
      user.organizations.map{|o| o.users + o.users_in_projects }.flatten.compact.each do |user|
        known_map[user.login] = user
      end

      map = {}
      users.each do |user|
        map[user['username']] = known_map[user['username']].try(:login)
      end
      self[:user_map] = map
    end
    self[:user_map]
  end

  def type_name
    TYPE_CODES[type_id]
  end
  
  def type_name=(value)
    self.type_id = TYPE_LOOKUP[value.to_sym]
  end
  
  def status_name
    type_id == 0 ? IMPORT_STATUS_NAMES[status] : EXPORT_STATUS_NAMES[status]
  end
  
  def status_name=(value)
    self.status = type_id == 0 ? IMPORT_STATUSES[value] : EXPORT_STATUSES[value]
  end
  
  def projects=(value)
    self.project_ids = Array(value).map(&:to_i).compact
  end
  
  def project_ids=(value)
    self[:project_ids] = Array(value).map(&:to_i).compact
  end
  
  def projects
    if user
      Project.where(:id => project_ids, :organization_id => user.admin_organization_ids).all
    else
      Project.where(:id => project_ids).all
    end
  end
  
  def organizations_to_export
    if user
      Organization.where(:projects => {:id => project_ids, :organization_id => user.admin_organization_ids}).joins([:projects]).all
    else
      Organization.where(:projects => {:id => project_ids}).joins([:projects]).all
    end
  end

  def data
    if @data.nil? and type_name == :import
      begin
        data_path = processed_data.path
        if Teambox.config.amazon_s3
          fetch_s3_upload
          data_path = "#{Rails.root}/tmp/#{processed_data.path}"
        end
        File.open(data_path) do |f|
          @data = if service == 'basecamp'
            Hash.from_xml f.read
          else
            ActiveSupport::JSON.decode f.read
          end
        end
      rescue
        nil
      end
    else
      @data
    end
  end
end

app/models/teambox_data/validations.rb
class TeamboxData
  validate :map_must_be_known
  validate :must_be_admin_of_target_organization
  validates_inclusion_of :service, :in => %(teambox basecamp)

  def must_be_admin_of_target_organization
    @errors.add("organization_id", "Should be an admin") if !user.admin_organizations.map(&:id).include?(organization_id) && status_name != :uploading && type_name == :import
  end

  #We check that we know all the users in the user map
  def map_must_be_known
    if type_name == :import and status_name == :mapping
      # All users need to be known to the owner
      users = user.users_for_user_map.map(&:login)

      user_map.each do |login,dest_login|
        if !users.include?(dest_login.to_s.strip)
          @errors.add "user_map_#{login}", "#{dest_login} Not known to user"
        end
      end
    end
  end

end

app/controllers/teambox_datas_controller.rb
class TeamboxDatasController < ApplicationController
  skip_before_filter :load_project
  before_filter :find_data, :except => [:index, :new, :create]
  
  def index
    # show current imports/exports
    @data_imports = current_user.teambox_datas.find_all_by_type_id(0)
    @data_exports = current_user.teambox_datas.find_all_by_type_id(1)
    
    respond_to do |f|
      f.html
    end
  end
  
  def show
    respond_to do |f|
      if @data.type_name == :import and @data.need_data? and @data.data == nil
        @data.status_name = :uploading
        @data.save
        flash.now[:error] = t('teambox_datas.show_import.import_error')
        f.html { render view_for_data(:show) }
      else
        f.html { render view_for_data(:show) }
      end
    end
  end
  
  def new
    @data = current_user.teambox_datas.build(:service => 'teambox')
    @data.type_name = params[:type]
    
    respond_to do |f|
      f.html { render view_for_data(:new) }
    end
  end
  
  def create
    @data = current_user.teambox_datas.build(params[:teambox_data])
    if @data.save
      redirect_to teambox_data_path(@data)
    else
      flash.now[:error] = "There were errors with the information you supplied!"
      render view_for_data(:new)
    end
  end
  
  def update
    #TODO: Refactor this mess, along with the model
    return redirect_to(@data) if @data.processing?
    unless @data.update_attributes(params[:teambox_data])
      flash.now[:error] = t('teambox_datas.show_import.import_error')
    else
      flash.now[:error] = "There were errors with the information you supplied!" if !@data.processing?
    end
    render view_for_data(:show)
  end
  
  def destroy
    @data.destroy
    
    respond_to do |f|
      f.html { redirect_to teambox_datas_path }
    end
  end
  
  def download
    head(:forbidden) and return unless @data.downloadable?(current_user)
    
    if Teambox.config.amazon_s3
      redirect_to @data.processed_data.url
    else
      path = @data.processed_data.path
      unless File.exist?(path)
        head(:bad_request)
        raise "Unable to download file"
      end

      mime_type = File.mime_type?(@data.processed_data_file_name)
      mime_type = 'application/octet-stream' if mime_type == 'unknown/unknown'

      send_file_options = { :type => mime_type }
      response.headers['Cache-Control'] = 'private, max-age=31557600'

      send_file(path, send_file_options)
    end
  end
  
private

  def find_data
    unless @data = TeamboxData.find_by_id(params[:id])
      flash[:error] = t('not_found.data')
      redirect_to teambox_datas_path
    end
  end
  
  def view_for_data(action)
    "#{action}_#{@data.type_name}"
  end
  
end

app/helpers/teambox_datas_helper.rb
module TeamboxDatasHelper
  def new_teambox_export_link
    link_to content_tag(:span,"Export"), new_teambox_data_path(:type => :export), :class => 'add_button'
  end
  
  def new_teambox_import_link
    link_to content_tag(:span,"Import"), new_teambox_data_path(:type => :import), :class => 'add_button'
  end
  
  def options_for_user_map
    [['Please Select...', '#invalid']] + current_user.users_for_user_map.map do |user|
      ["#{user.to_s} (@#{user.login})", user.login]
    end
  end
  
  def options_for_organization
    [['Please Select...', '#invalid']] + current_user.admin_organizations.map do |organization|
      ["#{organization}", organization.id]
    end
  end
  
  def autocomplete_import_users
    format = '%s <span class="informal">%s</span>'
    data_by_permalink = {}
    
    names = current_user.users_for_user_map.map do |user, data|
      (format % [user.login, "#{h user.first_name} #{h user.last_name}"])
    end
    
    javascript_tag "_import_users_autocomplete = #{names.to_json}"
  end
  
  def fields_for_teambox_export(form, data)
    render :partial => 'teambox_datas/export_fields', :locals => {:f => form, :data => data}
  end
  
  def map_table_for_data(teambox_data)
    render :partial => 'user_map',
           :collection => teambox_data.user_map.map{|key,value|[key,value]},
           :locals => {:users => teambox_data.users_lookup}
  end
end

app/views/teambox_datas/_data.haml
.teambox_data
  .info
    %p= link_to "#{data.created_at.to_s}", teambox_data_path(data)
    %p.desc
      - if data.processing?
        = t('.processing')
      - elsif !data.processed_at.nil?
        %strong= data.projects.map(&:to_s).join(',')
        = t('.processed_at', :processed_at => data.processed_at)
      - else
        = t('.incomplete')
  .actions
    = link_to t(data.processing?||data.need_data? ? 'common.cancel' : '.remove'), teambox_data_path(data, :anchor => 'destroy'),
      'data-confirm' => t('.confirm_delete'), 'data-method' => 'delete', 'data-remote' => true
  .clear

app/views/teambox_datas/_export_fields.haml
- if @data.status_name == :selecting
  %p= t('.description')

  .projects
    - for organization in current_user.admin_organizations
      - if organization.projects.any?
        %h3= h(organization.name)
        - for project in organization.projects
          .project
            = check_box_tag 'teambox_data[project_ids][]', project.id, false, :id => "teambox_project_#{project.id}"
            %label{:for => "teambox_project_#{project.id}"}= h project.name
  

app/views/teambox_datas/_import_fields.haml
- if @data.status_name == :uploading
  %h3= t('.service')
  .service
    = f.radio_button :service, 'teambox'
    = f.label :service_teambox, 'Teambox'
  .service
    = f.radio_button :service, 'basecamp'
    = f.label :service_basecamp, 'Basecamp'
  
  .many_fields
    = f.label :processed_data, t('.select_file')
    = f.file_field :processed_data, :size => 20
    .clear
- elsif @data.status_name == :mapping
  %p= t('.please_supply_user_map')
  %table#map_users
    %tr
      %th= t('.user')
      %th= t('.teambox_user')
      %th
    = map_table_for_data(@data)
  .target_project.many_fields
    %label{:for => 'teambox_data_organization_id'}= t('.in_organization')
    = select_tag "teambox_data[organization_id]", options_for_select(options_for_organization, @data.organization_id)
    = errors_for @data, "organization_id"

app/views/teambox_datas/_user_map.haml
= autocomplete_import_users
- user = users[user_map[0]]
%tr{:class => ''}
  %td
    %label{:for => "user_map_#{user_map[0]}"}= "#{user['first_name']} #{user['last_name']} (@#{user_map[0]})"
  %td=  text_field_tag "teambox_data[user_map][#{user_map[0]}]", user_map[1], :id => "user_map_#{user_map[0]}", :class => 'user'
  %td=  errors_for @data, "user_map_#{user_map[0]}"

app/views/teambox_datas/index.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')
%p
  You can import and export your account information at any moment.
  %br
  Teambox produces standard JSON documents that you can import from any system supporting it.


%h3= t('.imports')
#data_imports
  %p= t('.imports_explain')
  - if @data_imports.any?
    = render :partial => 'data', :collection => @data_imports
  - else
    %p= t('.no_imports')

  = new_teambox_import_link

%h3= t('.exports')

#data_exports
  - if @data_exports.any?
    = render :partial => 'data', :collection => @data_exports
  - else
    %p= t('.no_exports')

  = new_teambox_export_link

app/views/teambox_datas/new_export.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')

= form_for @data do |f|
  = hidden_field_tag 'teambox_data[type_name]', 'export'
  = fields_for_teambox_export(f, @data)
  .submit
    = f.submit t('.submit')
    = t('common.or')
    = link_to t('common.cancel'), teambox_datas_path

app/views/teambox_datas/new_import.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')

= form_for @data, :html => {:multipart => true} do |f|
  = hidden_field_tag 'teambox_data[type_name]', 'import'
  = render :partial => 'teambox_datas/import_fields', :locals => {:f => f, :data => @data}
  .submit
    = f.submit t('.submit')
    = t('common.or')
    = link_to t('common.cancel'), teambox_datas_path

app/views/teambox_datas/show_export.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2
  = t('.title')

.teambox_data
  - if @data.processing?
    %p= t('teambox_datas.data.processing')
    .actions
      %a{:href => teambox_data_path(@data), :class => 'cancel', 'data-method' => 'delete'}= t('common.cancel')
  - else
    %p= t('teambox_datas.data.processed_at', :processed_at => @data.processed_at)

  %p= t('.projects')
  %ul
    - @data.projects.each do |project|
      %li= link_to h(project.name), project_path(project)

  - unless @data.processing?
    %p= link_to t('.download'), download_teambox_data_path(@data)

app/views/teambox_datas/show_import.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')

- if @data.need_data?
  = form_for @data, :html => {:multipart => true} do |f|
    = render :partial => 'teambox_datas/import_fields', :locals => {:f => f, :data => @data}
    .submit
      = f.submit t('.submit')
      = t('common.or')
      = link_to t('common.cancel'), @data, :class => 'cancel', :"data-method" => :delete
- elsif @data.processed_at
  %p= t('teambox_datas.data.processed_at', :processed_at => @data.processed_at)
  %p= t('.projects')
  %ul
    - @data.projects.each do |project|
      %li= link_to h(project.name), project_path(project)
- elsif @data.processing?
  %p= t('teambox_datas.data.processing')
  = link_to t('common.cancel'), @data, :class => 'cancel', :"data-method" => :delete
- else
  %p= t('.import_error')	
  = link_to t('common.cancel'), @data, :class => 'cancel', :"data-method" => :delete