config/routes.rb
Teambox::Application.routes.draw do

  # If secure_logins is true, constrain matches to ssl requests
  class SSLConstraints
    def self.matches?(request)
      !Teambox.config.secure_logins || request.ssl?
    end
  end

  resources :sites, :only => [:show, :new, :create]

  match '/public' => 'public/projects#index', :as => :public_projects
  match '/goodbye' => 'static_pages#goodbye', :as => :goodbye 

  namespace :public do
    match ':id' => 'projects#show', :as => :project
    match ':project_id/conversations' => 'conversations#index', :as => :project_conversations
    match ':project_id/conversations/:id' => 'conversations#show', :as => :project_conversation
    match ':project_id/:id' => 'pages#show', :as => :project_page
  end

  match 'api' => 'apidocs#index', :as => :api
  match 'api/concepts' => 'apidocs#concepts', :as => :api_concepts
  match 'api/routes' => 'apidocs#routes', :as => :api_routes
  match 'api/auth' => 'apidocs#auth', :as => :api_auth
  match 'api/changes' => 'apidocs#changes', :as => :api_changes
  match 'api/:model' => 'apidocs#model', :as => :api_model

  resources :sprockets, :only => [:index, :show]

  #Constrain all requests to the ssl constraint
  scope :constraints => SSLConstraints do

    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/login/:username' => 'sessions#backdoor', :as => :login_backdoor if Rails.env.cucumber?

    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup

    match '/search' => 'search#index', :as => :search

    match '/guides' => 'guides#index', :as => :guides

    match '/text_styles' => 'users#text_styles', :as => :text_styles
    match '/email_posts_path' => 'users#email_posts', :as => :email_posts
    match '/invite_format' => 'invitations#invite_format', :as => :invite_format
    match '/feeds' => 'users#feeds', :as => :feeds
    match '/calendars' => 'users#calendars', :as => :calendars
    match '/disable_splash' => 'users#disable_splash', :as => :disable_splash
    match '/forgot' => 'reset_passwords#new', :as => :forgot_password
    match '/reset/:reset_code' => 'reset_passwords#reset', :as => :reset_password
    match '/forgetting' => 'reset_passwords#update_after_forgetting', :as => :update_after_forgetting, :method => :put
    match '/reset_password_sent' => 'reset_passwords#sent', :as => :sent_password

    match '/format/:f' => 'sessions#change_format', :as => :change_format

    match '/projects/:project_id/invite/:login' => 'invitations#create', :as => :create_project_invitation, :method => :post

    match '/auth/:provider/callback' => 'auth#callback', :as => :auth_callback
    match '/auth/failure' => 'auth#failure', :as => :auth_failure
    match '/complete_signup' => 'users#complete_signup', :as => :complete_signup
    match '/auth/:provider/unlink' => 'users#unlink_app', :as => :unlink_app

    resources :google_docs do
      get :search, :on => :collection
    end
    
    resources :google_calendars

    #RAILS 3 Useless resource?
    resources :reset_passwords
    resource :session

    resources :organizations do
      member do
        get :projects
        get :external_view
        get :delete
        get :appearance
        put :update_appearance
      end
      resources :memberships do
        member do
          get :change_role
          get :add
          get :remove
        end
      end
      resources :task_list_templates do
        collection do
          put :reorder
        end
      end
    end

    match '/account/settings' => 'users#edit', :as => :account_settings, :sub_action => 'settings'
    match '/account/picture' => 'users#edit', :as => :account_picture, :sub_action => 'picture'
    match '/account/profile' => 'users#edit', :as => :account_profile, :sub_action => 'profile'
    match '/account/linked_accounts' => 'users#edit', :as => :account_linked_accounts, :sub_action => 'linked_accounts'
    match '/account/notifications' => 'users#edit', :as => :account_notifications, :sub_action => 'notifications'
    match '/account/delete' => 'users#edit', :as => :account_delete, :sub_action => 'delete'
    match '/account/destroy' => 'users#destroy', :as => :destroy_user
    match '/account/activity_feed_mode/collapsed' => 'users#change_activities_mode', :as => :collapse_activities, :collapsed => true
    match '/account/activity_feed_mode/expanded' => 'users#change_activities_mode', :as => :expand_activities, :collapsed => false
    match '/account/watch_list' => 'watchers#index', :as => :watch_list
    post  '/account/watch_list/unwatch/:watch_id' => 'watchers#unwatch', :as => :unwatch
    post  '/account/stats/:stat/inc' => 'users#increment_stat'
    post  '/account/badge/:badge/grant' => 'users#grant_badge'
    post  '/account/first_steps/hide' => 'users#hide_first_steps'

    resources :teambox_datas, :path => '/datas' do
      member do
        get :download
      end
    end

    resources :users do
      resources :invitations
      member do
        get :confirm_email
        get :unconfirmed_email
        get :contact_importer
      end
      resources :conversations
      resources :task_lists do
        resources :tasks
      end
      match 'activities/users/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    end

    match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
    match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    match 'activities/:id/show_thread(.:format)' => 'activities#show_thread', :as => :show_thread, :method => :get

    match 'projects/archived.:format' => 'projects#index', :as => :project_archived, :sub_action => 'archived'

    match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

    resources :projects do
      member do
        post :accept
        post :decline
        get :join
      end

      match 'time/:year/:month' => 'hours#index', :as => :hours_by_month, :via => :get
      match 'time/by_period' => 'hours#by_period', :as => :hours_by_period, :via => :get
      match 'time' => 'hours#index', :as => :time
      match 'settings' => 'projects#edit', :as => :settings, :sub_action => 'settings'
      match 'picture' => 'projects#edit', :as => :picture, :sub_action => 'picture'
      match 'deletion' => 'projects#edit', :as => :deletion, :sub_action => 'deletion'
      match 'ownership' => 'projects#edit', :as => :ownership, :sub_action => 'ownership'

      resources :invitations do
        member do
          put :accept
          put :decline
          get :resend
        end
      end

      match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
      match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get

      match 'move/:id' => 'uploads#move', :via => :put, :as => :move_resource

      resources :uploads do
        member do
          get :public_download
          put :rename
        end
        collection do
          resources :folders, :except => [:show, :index, :new] do
            member do
              get :public_download, :controller => 'uploads', :action => 'public_download'
              put :rename
            end
          end
        end
      end

      match 'downloadable/:id/email_public' => "uploads#email_public", :via => :post, :as => :email_public_download
      
      match 'uploads/folders/:id' => 'uploads#index', :via => :get
      match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

      match 'invite_people' => 'projects#invite_people', :as => :invite_people, :via => :get
      match 'invite_people' => 'projects#send_invites', :as => :send_invites, :via => :post

      resources :tasks do
        member do
          put :reorder
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :task_lists do
        collection do
          get :gantt_view
          get :archived
          put :reorder
        end
        member do
          put :archive
          put :unarchive
          put :watch
          put :unwatch
        end

        resources :tasks do
          member do
            put :watch
            put :unwatch
          end

          resources :comments
        end
      end

      match 'contacts' => 'people#contacts', :as => :contacts, :method => :get

      resources :people do
        member do
          get :destroy
        end
      end

      resources :conversations do
        member do
          put :convert_to_task
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :pages do
        collection do
          post :resort
        end
        member do
          post :reorder
          put :watch
          put :unwatch
        end
        # In rails 2, we have :pages, :has_many => :task_list ?!
        resources :notes,:dividers,:uploads
      end

      match 'search' => 'search#index', :as => :search

      resources :google_docs do
        collection do
          :search
        end
        member do
          put :write_access, :path => "write_access/:access", :access => /lock|unlock/
        end
      end
    end

    namespace :api_v1, :path => 'api/1' do
      resources :app_links, :except => [ :edit, :update ]
      resources :projects, :except => [:new, :edit] do

        resources :activities, :only => [:index, :show]

        resources :people, :except => [:create, :new, :edit]

        resources :comments, :except => [:new, :create, :edit]

        resources :conversations, :except => [:new, :edit] do
          member do
            put :watch
            put :unwatch
            post :convert_to_task
          end

          resources :comments, :except => [:new, :edit]
        end

app/models/conversation/conversions.rb
class Conversation
  def to_xml(options = {})
    options[:indent] ||= 2
    xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])
    xml.instruct! unless options[:skip_instruct]
    xml.conversation :id => id do
      xml.tag! 'project-id',      project_id
      xml.tag! 'user-id',         user_id
      xml.tag! 'name',            name
      xml.tag! 'created-at',      created_at.to_s(:db)
      xml.tag! 'updated-at',      updated_at.to_s(:db)
      xml.tag! 'watchers',        watcher_ids.join(',')
      if Array(options[:include]).include? :comments
        comments.to_xml(options.merge({ :skip_instruct => true }))
      end
    end
  end
  
  def to_api_hash(options = {})
    base = {
      :id => id,
      :project_id => project_id,
      :user_id => user_id,
      :name => name,
      :simple => simple,
      :created_at => created_at.to_s(:api_time),
      :updated_at => updated_at.to_s(:api_time),
      :watchers => Array.wrap(watcher_ids),
      :comments_count => comments_count,
      :is_private => is_private
    }
    
    base[:type] = self.class.to_s if options[:emit_type]
    
    if Array(options[:include]).include? :thread_comments
      base[:first_comment] = first_comment.to_api_hash(options)  if first_comment
      base[:recent_comments] = recent_comments.map{|c|c.to_api_hash(options)}
    elsif !Array(options[:include]).include?(:comments)
      base[:first_comment_id] = first_comment.try(:id)
      base[:recent_comment_ids] = recent_comments.map{|c|c.id}
    end
    
    if Array(options[:include]).include? :comments
      base[:comments] = comments.map{|c| c.to_api_hash(options)}
    end
    
    base
  end
end

app/controllers/api_v1/conversations_controller.rb
class ApiV1::ConversationsController < ApiV1::APIController
  before_filter :load_conversation, :except => [:index, :create]
  
  def index
    authorize! :show, @current_project||current_user
    
    context = if @current_project
      @current_project.conversations.where(api_scope)
    else
      Conversation.joins(:project).where(:project_id => current_user.project_ids, :projects => {:archived => false}).where(api_scope)
    end
    
    @conversations = context.except(:order).
                             where(api_range('conversations')).
                             where(['is_private = ? OR (is_private = ? AND watchers.user_id = ?)', false, true, current_user.id]).
                             joins("LEFT JOIN watchers ON (conversations.id = watchers.watchable_id AND watchers.watchable_type = 'Conversation') AND watchers.user_id = #{current_user.id}").
                             limit(api_limit).
                             order('conversations.id DESC')
    
    api_respond @conversations, :references => true
  end

  def show
    authorize! :show, @conversation
    api_respond @conversation, :include => api_include, :references => true
  end
  
  def create
    authorize! :converse, @current_project
    @conversation = @current_project.conversations.new_by_user(current_user, params)
    @conversation.is_private = (params[:conversation][:is_private]||false) if params[:conversation]
    
    if @conversation.save
      handle_api_success(@conversation, :is_new => true, :references => true, :include => [:user, :uploads, :google_docs])
    else
      handle_api_error(@conversation)
    end
  end
  
  def update
    authorize! :update, @conversation

    @conversation.updating_user = current_user

    if @conversation.update_attributes params
      handle_api_success(@conversation, :wrap_objects => true, :references => true, :include => [:user, :uploads, :google_docs])
    else
      handle_api_error(@conversation)
    end
  end

  def destroy
    authorize! :destroy, @conversation
    @conversation.destroy
    handle_api_success(@conversation)
  end
  
  def convert_to_task
    authorize! :update, @conversation

    @conversation.attributes = params
    @conversation.updating_user = current_user
    @conversation.comments_attributes = {"0" => params[:comment]} if params[:comment]

    success = @conversation.save
    if success
      @task = @conversation.convert_to_task!
      success = @task && @task.errors.empty?
    end

    if success
      handle_api_success(@task, :is_new => true, :include => [:comments])
    else
      handle_api_error(@task||@conversation)
    end
  end
  
  def watch
    authorize! :update, @conversation
    @conversation.add_watcher(current_user)
    handle_api_success(@conversation)
  end

  def unwatch
    authorize! :update, @conversation
    @conversation.remove_watcher(current_user)
    handle_api_success(@conversation)
  end

  protected
  
  def load_conversation
    @conversation = if @current_project
      @current_project.conversations.find_by_id(params[:id])
    else
      Conversation.where(:project_id => current_user.project_ids).find_by_id(params[:id])
    end
    api_error :not_found, :type => 'ObjectNotFound', :message => 'Conversation not found' unless @conversation
  end
  
  def api_scope
    conditions = {}
    if params[:type]
      case params[:type]
      when 'thread'
        conditions[:simple] = true
      when 'conversation'
        conditions[:simple] = false
      end
    end
    unless params[:user_id].nil?
      conditions[:user_id] = params[:user_id].to_i
    end
    conditions
  end
  
  def add_watchers(hash)
    (hash || []).each do |user_id, should_notify|
      if should_notify == "1" and Person.exists? :project_id => @conversation.project_id, :user_id => user_id
        user = User.find user_id
        @conversation.add_watcher user# if user
      end
    end
  end
    
  def api_include
    [:comments, :user, :uploads] & (params[:include]||{}).map(&:to_sym)
  end
  
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  
  def conversations_primer(project)
    if project.editable?(current_user)
      render 'conversations/primer', :project => project
    end
  end

  def new_conversation_link(project)
    link_to content_tag(:span, t('.new_conversation')), new_project_conversation_path(project), 
      :class => 'add_button', :title => 'new_conversation_link'
  end

  def conversation_comment(conversation)
    if comment = conversation.comments.first
      render 'comments/comment', :comment => comment
    end
  end
  
  def conversation_comments_count(conversation)
    pluralize(conversation.comments.size, t('.message'), t('.messages'))
  end
  
  def conversation_column(project,conversations,options={})
    options[:conversation] ||= nil
    options[:show_conversation_settings] ||= false
    
    render 'conversations/column',
      :project => project,
      :conversations => conversations,
      :conversation => options[:conversation],
      :show_conversation_settings =>  options[:show_conversation_settings]
  end

end

app/views/conversations/_column.haml
- content_for :column do
  .conversations
    = render conversations, :project => project, :current_target => conversation

app/views/conversations/_conversation.haml
- classes = "conversation_item"
- classes += ' active' if defined?(current_target) && current_target == conversation
.conversation{ :id => "Conversation_#{conversation.id}", :class => classes }
  %span.comments_count= conversation.comments_count
  - title = conversation.name.presence || t('activerecord.models.conversation')
  = link_to title, project_conversation_path(conversation.project,conversation), :class => 'conversation_link'
.clear

app/views/conversations/_fields.haml
.text_field.name
  = f.label :name, t('.name')
  = f.text_field :name
  = errors_for f.object, :name

- if f.object.new_record?
  = f.fields_for :comments, f.object.comments.build do |comment_fields|
    .field.text_area
      = comment_fields.text_area :body, :placeholder => t("comments.new.conversation")
    .extra
      .upload_area
        %p= t('uploads.new.select_a_file')
        - comment_fields.object.uploads.build
        = comment_fields.fields_for :uploads do |uploads|
          = uploads.file_field :asset, :id => 'upload_file'
      .private_options{ :style => 'display: none', 'object-prefix' => "conversation_new", 'object-type' => 'conversation[comments_attributes][0]' }
      .actions
        .attach
          %span= t('comments.fields.attach') + ": "
          = link_to t('uploads.comment_upload_link'), '#uploads', :class => 'attach_icon hoverable', :title => "Attach a file"
        = render 'google_docs/form', :f => comment_fields
        = link_to "Privacy", '#privacy', :class => 'private_switch hoverable', :title => "Control who can see this element"

app/views/conversations/_header.haml
.conversation_header

  - if can? :update, conversation
    .text_actions
      = link_to t('common.edit'), [:edit, project, conversation]
      
      - if can? :destroy, conversation
        = t('common.or')
        = link_to t('common.delete'), [project, conversation],
          :'data-method' => 'delete', :'data-confirm' => t('conversations.actions.confirm_delete'),
          :class => 'delete_conversation_link'
  
  %h2=h conversation.name

- if can? :update, conversation
  = form_for [project, conversation], :html => { :'data-remote' => true, :style => 'display: none', :class => 'edit_conversation app_form' } do |f|
    = render 'fields', :f => f, :project => @current_project
    .submit
      = f.submit t('conversations.edit.submit')
      = t('common.or')
      = link_to t('common.cancel'), '#cancel'

app/views/conversations/_primer.haml
#primer
  %p= t('.empty') if location_name?('index_conversations')
  %div{ :class => "#{ 'box' if location_name?('index_conversations')}"} 
    - if can?(:converse, project) && location_name?('index_conversations')
      %h2= link_to t('.create_first'), new_project_conversation_path(project)
    %p= t('.define_html')
    %ul
      %li= t('.item1_html')
      %li= t('.item2_html')
      %li= t('.item3_html')
      %li= t('.item4_html')
    %p= t('.footer1_html')
    %p= t('.footer2_html')

app/views/conversations/_short_conversation.haml
- if comment = conversation.comments.first(:order => 'id asc')
  .conversation
    .comment
      .info= thumb_avatar(comment.user)
      .block
        .body
          %h2.title
            - title = conversation.name.presence || t('activerecord.models.conversation')
            = link_to title, [@current_project, conversation]
            %span= t('common.comment', :count => conversation.comments_count)
          .textilized
            ~raw comment.body_html
          - if comment.uploads.any?
            - if comment.uploads.all? { |upload| upload.image? }
              .upload_images
                = list_uploads_inline_with_thumbnails(comment.uploads)
            - else
              .upload_list
                = list_uploads_inline(comment.uploads)
          %p.go_to_thread
            = link_to t('conversations.index.view_single'), [@current_project, conversation]
      .clear

app/views/conversations/_watcher_fields.haml
.watchers
  - if project.public
    %p= t('.cant_notify')
  - else
    - if project.users.size > 1
      %h3= t('.add_suscribers')

      .user_all
        %label
          = check_box_tag :user_all, "1", true, :name => nil
          = t('conversations.watcher_fields.people_all')
        
      - for user in project.users
        - unless user == current_user
          .user
            = check_box_tag 'conversation[watcher_ids][]', user.id, true, :id => "conversation_watcher_#{user.id}"
            %label{:for => "conversation_watcher_#{user.id}"}= user.name
          
      .clear
      %p= t('.subscribe_note_html')
    - else
      %h3= t('.invite_users')
      .clear
      %p= t('.no_users_yet_html', :invite_link => project_people_path(project))

app/views/conversations/index.html.haml
%h2= t('.title', :project => @current_project)

= conversation_column(@current_project,@conversations, :show_conversation_settings => true)

.create_bar
  - if can? :converse, @current_project
    = new_conversation_link(@current_project)
    = t('common.or')
    = instructions_for_email(@current_project)
  - else
    = t('.cant_create')

- if @conversations.any?
  #conversations
    = render :partial => 'conversations/short_conversation', :as => :conversation, :collection => @conversations
- else
  = conversations_primer(@current_project)

app/views/conversations/index.m.haml
#page
  #conversations
    .conversation
      = link_to t('.new_conversation'), new_project_conversation_path(@current_project), :class => 'new'
    - for conversation in @conversations
      .conversation
        = link_to h(conversation), project_conversation_path(@current_project, conversation)

app/views/conversations/new.haml
- content_for :column do
  = conversations_primer(@current_project)
  = instructions_for_email(@current_project)

%h2= t('.title')

= form_for [@current_project, @conversation], :html => { 'data-project-id' => @current_project.id, :multipart => true } do |f|
  = render 'fields', :f => f, :project => @current_project
  = render 'watcher_fields', :f => f, :project => @current_project
  .submit
    %span.help= formatting_documentation_link
    = preview_button
    = f.submit t('.submit')

app/views/conversations/show.html.haml
= conversation_column(@current_project, @conversations, :conversation => @conversation)
= render 'conversations/header', :project => @current_project, :conversation => @conversation

= people_watching(@current_project,current_user,@conversation)
= render 'activities/thread', :thread => @conversation

app/views/conversations/show.m.haml
%h2=h @conversation

= people_watching(@current_project,current_user,@conversation)

#page
  #activities
    = list_comments(@conversation.comments,@conversation)

- if can? :comment, @conversation
  = form_for [@current_project, @conversation, @conversation.comments.build], :html => {:id => nil, 'data-project-id' => @current_project.id} do |form|
    = render 'comments/fields', :f => form, :placeholder => t("comments.new.conversation")