config/routes.rb
Teambox::Application.routes.draw do

  # If secure_logins is true, constrain matches to ssl requests
  class SSLConstraints
    def self.matches?(request)
      !Teambox.config.secure_logins || request.ssl?
    end
  end

  resources :sites, :only => [:show, :new, :create]

  match '/public' => 'public/projects#index', :as => :public_projects
  match '/goodbye' => 'static_pages#goodbye', :as => :goodbye 

  namespace :public do
    match ':id' => 'projects#show', :as => :project
    match ':project_id/conversations' => 'conversations#index', :as => :project_conversations
    match ':project_id/conversations/:id' => 'conversations#show', :as => :project_conversation
    match ':project_id/:id' => 'pages#show', :as => :project_page
  end

  match 'api' => 'apidocs#index', :as => :api
  match 'api/concepts' => 'apidocs#concepts', :as => :api_concepts
  match 'api/routes' => 'apidocs#routes', :as => :api_routes
  match 'api/auth' => 'apidocs#auth', :as => :api_auth
  match 'api/changes' => 'apidocs#changes', :as => :api_changes
  match 'api/:model' => 'apidocs#model', :as => :api_model

  resources :sprockets, :only => [:index, :show]

  #Constrain all requests to the ssl constraint
  scope :constraints => SSLConstraints do

    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/login/:username' => 'sessions#backdoor', :as => :login_backdoor if Rails.env.cucumber?

    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup

    match '/search' => 'search#index', :as => :search

    match '/guides' => 'guides#index', :as => :guides

    match '/text_styles' => 'users#text_styles', :as => :text_styles
    match '/email_posts_path' => 'users#email_posts', :as => :email_posts
    match '/invite_format' => 'invitations#invite_format', :as => :invite_format
    match '/feeds' => 'users#feeds', :as => :feeds
    match '/calendars' => 'users#calendars', :as => :calendars
    match '/disable_splash' => 'users#disable_splash', :as => :disable_splash
    match '/forgot' => 'reset_passwords#new', :as => :forgot_password
    match '/reset/:reset_code' => 'reset_passwords#reset', :as => :reset_password
    match '/forgetting' => 'reset_passwords#update_after_forgetting', :as => :update_after_forgetting, :method => :put
    match '/reset_password_sent' => 'reset_passwords#sent', :as => :sent_password

    match '/format/:f' => 'sessions#change_format', :as => :change_format

    match '/projects/:project_id/invite/:login' => 'invitations#create', :as => :create_project_invitation, :method => :post

    match '/auth/:provider/callback' => 'auth#callback', :as => :auth_callback
    match '/auth/failure' => 'auth#failure', :as => :auth_failure
    match '/complete_signup' => 'users#complete_signup', :as => :complete_signup
    match '/auth/:provider/unlink' => 'users#unlink_app', :as => :unlink_app

    resources :google_docs do
      get :search, :on => :collection
    end
    
    resources :google_calendars

    #RAILS 3 Useless resource?
    resources :reset_passwords
    resource :session

    resources :organizations do
      member do
        get :projects
        get :external_view
        get :delete
        get :appearance
        put :update_appearance
      end
      resources :memberships do
        member do
          get :change_role
          get :add
          get :remove
        end
      end
      resources :task_list_templates do
        collection do
          put :reorder
        end
      end
    end

    match '/account/settings' => 'users#edit', :as => :account_settings, :sub_action => 'settings'
    match '/account/picture' => 'users#edit', :as => :account_picture, :sub_action => 'picture'
    match '/account/profile' => 'users#edit', :as => :account_profile, :sub_action => 'profile'
    match '/account/linked_accounts' => 'users#edit', :as => :account_linked_accounts, :sub_action => 'linked_accounts'
    match '/account/notifications' => 'users#edit', :as => :account_notifications, :sub_action => 'notifications'
    match '/account/delete' => 'users#edit', :as => :account_delete, :sub_action => 'delete'
    match '/account/destroy' => 'users#destroy', :as => :destroy_user
    match '/account/activity_feed_mode/collapsed' => 'users#change_activities_mode', :as => :collapse_activities, :collapsed => true
    match '/account/activity_feed_mode/expanded' => 'users#change_activities_mode', :as => :expand_activities, :collapsed => false
    match '/account/watch_list' => 'watchers#index', :as => :watch_list
    post  '/account/watch_list/unwatch/:watch_id' => 'watchers#unwatch', :as => :unwatch
    post  '/account/stats/:stat/inc' => 'users#increment_stat'
    post  '/account/badge/:badge/grant' => 'users#grant_badge'
    post  '/account/first_steps/hide' => 'users#hide_first_steps'

    resources :teambox_datas, :path => '/datas' do
      member do
        get :download
      end
    end

    resources :users do
      resources :invitations
      member do
        get :confirm_email
        get :unconfirmed_email
        get :contact_importer
      end
      resources :conversations
      resources :task_lists do
        resources :tasks
      end
      match 'activities/users/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    end

    match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
    match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    match 'activities/:id/show_thread(.:format)' => 'activities#show_thread', :as => :show_thread, :method => :get

    match 'projects/archived.:format' => 'projects#index', :as => :project_archived, :sub_action => 'archived'

    match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

    resources :projects do
      member do
        post :accept
        post :decline
        get :join
      end

      match 'time/:year/:month' => 'hours#index', :as => :hours_by_month, :via => :get
      match 'time/by_period' => 'hours#by_period', :as => :hours_by_period, :via => :get
      match 'time' => 'hours#index', :as => :time
      match 'settings' => 'projects#edit', :as => :settings, :sub_action => 'settings'
      match 'picture' => 'projects#edit', :as => :picture, :sub_action => 'picture'
      match 'deletion' => 'projects#edit', :as => :deletion, :sub_action => 'deletion'
      match 'ownership' => 'projects#edit', :as => :ownership, :sub_action => 'ownership'

      resources :invitations do
        member do
          put :accept
          put :decline
          get :resend
        end
      end

      match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
      match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get

      match 'move/:id' => 'uploads#move', :via => :put, :as => :move_resource

      resources :uploads do
        member do
          get :public_download
          put :rename
        end
        collection do
          resources :folders, :except => [:show, :index, :new] do
            member do
              get :public_download, :controller => 'uploads', :action => 'public_download'
              put :rename
            end
          end
        end
      end

      match 'downloadable/:id/email_public' => "uploads#email_public", :via => :post, :as => :email_public_download
      
      match 'uploads/folders/:id' => 'uploads#index', :via => :get
      match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

      match 'invite_people' => 'projects#invite_people', :as => :invite_people, :via => :get
      match 'invite_people' => 'projects#send_invites', :as => :send_invites, :via => :post

      resources :tasks do
        member do
          put :reorder
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :task_lists do
        collection do
          get :gantt_view
          get :archived
          put :reorder
        end
        member do
          put :archive
          put :unarchive
          put :watch
          put :unwatch
        end

        resources :tasks do
          member do
            put :watch
            put :unwatch
          end

          resources :comments
        end
      end

      match 'contacts' => 'people#contacts', :as => :contacts, :method => :get

      resources :people do
        member do
          get :destroy
        end
      end

      resources :conversations do
        member do
          put :convert_to_task
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :pages do
        collection do
          post :resort
        end
        member do
          post :reorder
          put :watch
          put :unwatch
        end
        # In rails 2, we have :pages, :has_many => :task_list ?!
        resources :notes,:dividers,:uploads
      end

      match 'search' => 'search#index', :as => :search

      resources :google_docs do
        collection do
          :search
        end
        member do
          put :write_access, :path => "write_access/:access", :access => /lock|unlock/
        end
      end
    end

    namespace :api_v1, :path => 'api/1' do
      resources :app_links, :except => [ :edit, :update ]
      resources :projects, :except => [:new, :edit] do

        resources :activities, :only => [:index, :show]

        resources :people, :except => [:create, :new, :edit]

        resources :comments, :except => [:new, :create, :edit]

        resources :conversations, :except => [:new, :edit] do
          member do
            put :watch
            put :unwatch
            post :convert_to_task
          end

          resources :comments, :except => [:new, :edit]
        end

app/models/user/activation.rb
class User

  attr_accessor :performing_reset

  def send_activation_email
    self.generate_login_code!
    Emailer.send_email :confirm_email, self.id
  end

  def send_reset_password
    self.generate_login_code!
    Emailer.send_email :reset_password, self.id
  end

  def is_active?
    Teambox.config.email_confirmation_require ? self.confirmed_user : true
  end

  def activate!
    self.confirmed_user = true
    self.save!
    self
  end
  
  def generate_login_code!
    self.login_token = ActiveSupport::SecureRandom.hex(20)
    self.login_token_expires_at = 1.month.from_now
    self.save(:validate => false)
  end
  
  def expire_login_code!
    self.login_token_expires_at = 1.minute.ago
    self.save!
  end
  
  def is_login_token_valid?(token)
    (token == self.login_token) and (self.login_token_expires_at > Time.now)
  end
  
end

app/models/user/authentication.rb
class User
  
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  
  attr_accessor :current_token
  
  def self.authenticate(login, password)
    unless login.blank? or password.blank?
      u = find_by_username_or_email(login)
      u && u.authenticated?(password) ? u : nil
    end
  end

end

app/models/user/avatar.rb
class User

  AvatarSizes = {
    :micro    => [24, 24],
    :thumb    => [48, 48],
    :profile  => [278, 500]
  }

  has_attached_file :avatar, 
    :url  => "/avatars/:id/:style.png",
    :path => (Teambox.config.amazon_s3 ? "avatars/:id/:style.png" : ":rails_root/public/avatars/:id/:style.png"),
    :styles => AvatarSizes.each_with_object({}) { |(name, size), all|
        all[name] = ["%dx%d%s" % [size[0], size[1], size[0] < size[1] ? '>' : '#'], :png]
      }

  attr_accessible :avatar, :avatar_destroy

  #validates_attachment_presence :avatar, :unless => Proc.new { |user| user.new_record? }
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar,
    :content_type => %w[image/jpeg image/pjpeg image/png image/x-png image/gif]
  
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end
  
  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end

  def avatar_or_gravatar_path(size, secure = false)
    (avatar? ? avatar.url(size) : gravatar(size, secure)).tap do |avatar_url|
      avatar_url.sub! 'http:', 'https:' if secure
    end
  end

  def avatar_or_gravatar_url(size = :thumb, secure = false)
    avatar_or_gravatar_path(size, secure).tap do |url|
      if url.starts_with? 'http'
        scheme = secure ? 'https:' : 'http:'
        url.sub('http:', scheme)
      else
        scheme = secure ? 'https:' : 'http:'
        url.replace '%s//%s%s' % [scheme, Teambox.config.app_domain, url]
      end
    end
  end
  
  def avatar_destroy
    false
  end
  
  def avatar_destroy=(value)
    self.avatar = nil if value and value != '0'
  end

  private

    def gravatar_id
      Digest::MD5.hexdigest email.downcase
    end

    def gravatar(size, secure = false, default = Teambox.config.gravatar_default)
      (secure ? 'https://secure.' : 'http://www.').tap do |url|
        url << "gravatar.com/avatar/#{gravatar_id}?size=#{AvatarSizes[size][0]}"
        url << "&default=#{default}" if default
      end
    end

end

app/models/user/badges.rb
class User

  attr_accessible :show_first_steps, :show_badges

  def badges
    settings['badges'] || []
  end

  def grant_badge(badge)
    write_setting 'badges',
      badges.push(badge).uniq
  end

  def show_badges
    !!settings['show_badges']
  end

  def show_badges=(v)
    self.settings = { 'show_badges' => v == "1" }
  end

  def show_first_steps
    !!settings['show_first_steps']
  end

  def show_first_steps=(v)
    self.settings = { 'show_first_steps' => v == "1" }
  end

end

app/models/user/conversions.rb
class User
  def to_api_hash(options = {})
    base = {
      :id => id,
      :first_name => first_name,
      :last_name => last_name,
      :locale => locale,
      :username => login,
      :time_zone => time_zone,
      :utc_offset => utc_offset,
      :biography => biography,
      :created_at => created_at.to_s(:api_time),
      :updated_at => updated_at.to_s(:api_time),
      :micro_avatar_url => avatar_or_gravatar_url(:micro),
      :avatar_url => avatar_or_gravatar_url(:thumb)
    }
    
    base[:type] = self.class.to_s if options[:emit_type]
    
    if Array(options[:include]).include? :email
      base[:email] = email
    end
    
    if Array(options[:include]).include? :projects
      base[:projects] = projects.map{|p| p.to_api_hash }
    end
    
    if Array(options[:include]).include? :organizations
      base[:organizations] = organizations.map{|o| o.to_api_hash }
    end
    
    base
  end
  
  def to_xml(options = {})
    options[:indent] ||= 2
    xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])
    xml.instruct! unless options[:skip_instruct]
    xml.user :id => id do
      xml.tag! 'first-name', first_name
      xml.tag! 'last-name', last_name
      # xml.tag! 'email', email
      xml.tag! 'locale', locale
      xml.tag! 'username', login
      xml.tag! 'time_zone', time_zone
      xml.tag! 'biography', biography
      xml.tag! 'created-at', created_at.to_s(:db)
      xml.tag! 'updated-at', updated_at.to_s(:db)
      xml.tag! 'avatar-url', avatar_or_gravatar_url(:thumb)
      xml.tag! 'micro-avatar-url', avatar_or_gravatar_url(:micro)
    end
  end
end

app/models/user/oauth.rb
class User
  has_many :client_applications
  has_many :tokens, :class_name=>"OauthToken",:order=>"authorized_at desc",:include=>[:client_application]
end

app/controllers/api_v1/users_controller.rb
class ApiV1::UsersController < ApiV1::APIController
  no_login_required :only => [ :create ]

  skip_before_filter :confirmed_user?, :only => [ :create ]
  before_filter :find_user, :only => [ :show, :update ]
  before_filter :load_invitation, :only => [ :create ]
  skip_before_filter :load_project
  
  def index
    authorize! :show, current_user
    
    @users = current_user.users_with_shared_projects.
      where(api_range('users')).
      limit(api_limit).
      order('id DESC')
    
    api_respond @users
  end

  def show
    authorize! :show, @user||current_user
    projects_shared = @user.projects_shared_with(@current_user)
    shares_invited_projects = projects_shared.empty? && @user.shares_invited_projects_with?(@current_user)
    
    if @user != @current_user and (!shares_invited_projects and projects_shared.empty?)
      api_error(:unauthorized, :type => 'InsufficientPermissions', :message => t('users.activation.invalid_user'))
    else
      api_respond @user
    end
  end

  def create
    logout_keeping_session!
    @user = User.new(params)

    @user.confirmed_user = (
      (@invitation && @invitation.email == @user.email) or
      !Teambox.config.email_confirmation_require)

    if @user.save
      self.current_user = @user

      handle_api_success(@user, :is_new => true)
    else
      handle_api_error(@user)
    end
  end

  def update
    authorize! :update, @user
    
    if @user.update_attributes(params)
      handle_api_success(@user)
    else
      handle_api_error(@user)
    end
  end

  def current
    api_respond current_user, :include => api_include+[:email], :extra_fields => {:api_version => API_VERSION}
  end

  protected
  
  def find_user
    unless @user = (User.find_by_login(params[:id]) || User.find_by_id(params[:id]))
      api_error(:not_found, :type => 'ObjectNotFound', :message => t('not_found.user'))
    end
  end  

  def load_invitation
    if params[:invitation]
      @invitation = Invitation.find_by_token(params[:invitation])
      @invitation_token = params[:invitation] if @invitation
    end
  end
  
  def api_include
    [:projects, :organizations] & (params[:include]||{}).map(&:to_sym)
  end
  
end

app/views/users/form/_delete.haml
- if current_user.projects.count > 0
  %p= t('.steps_before_1')
  %p= t('.steps_before_2')
  %p= t('.steps_before_3')
- else
  %p= t('.what_will_happen')
  %p= link_to t('.delete_my_account'), destroy_user_path

app/views/users/form/_linked_accounts.haml
- if Teambox.config.providers? and !Teambox.config.providers.empty?
  - Teambox.config.providers.each do |provider|
    %p{:id => provider[:provider].downcase}
      - if current_user.app_links.find_by_provider(provider[:provider])
        = t(:'oauth.your_account_is_linked_html', :provider => provider[:provider].titleize)
        = link_to t(:'oauth.unlink_account'), unlink_app_path(provider[:provider])
      - else
        = t(:'oauth.your_account_is_not_linked_html', :provider => provider[:provider].titleize)
        = link_to t(:'oauth.link_account'), "#{OmniAuth.config.path_prefix}/#{provider[:provider]}"

app/views/users/form/_new.haml
- if @invitation_token
  = hidden_field_tag 'invitation', @invitation_token

.first_name.text_field
  = f.label :first_name, t('users.form.first_name')
  = f.text_field :first_name, :autofocus => 'autofocus'
  = errors_for user, :first_name
.last_name.text_field
  = f.label :last_name, t('users.form.last_name')
  = f.text_field :last_name
  = errors_for user, :last_name
.email.text_field
  = f.label :email, t('users.form.email')
  - if (@invitation || @app_link)
    = f.text_field :email, :readonly => 'readonly', :style => 'color: #999'
  - else
    = f.text_field :email
  = errors_for user, :email
- if @invitation
  .use_this_email{ :style => 'margin: 10px; padding: 10px; border: 1px rgb(220,220,150) solid; background-color: rgb(255,255,200)' }
    = t('.use_this_email')

.language.select
  = f.label :locale, t('users.form.language')
  = f.select :locale, locale_select_values

.time_zone.select
  = f.label :time_zone, t('users.form.time_zone')
  = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Eastern Time (US & Canada)"

- if !@invitation
  - user.organizations.build
  = f.fields_for :organization do |organization|
    %fieldset.account
      %legend= t('.organization.title')
      %p
        = t('.organization.explain1')
        %br
        = t('.organization.explain2')
      .login.text_field
        = organization.label :name, t('.organization.label')
        = organization.text_field :name
        .field_note= t('.organization.field_note')

%fieldset.account
  %legend= t('.account.title')
  %p
    = t('.account.choose_username')
    %br
    = t('.account.validations')
  .login.text_field
    = f.label :login, t('users.form.login')
    = f.text_field :login
    = errors_for user, :login
    .field_note= t('.account.field_note')
  .password.text_field
    = f.label :password, t('users.form.password')
    = f.password_field :password, :autocomplete => 'off'
    = errors_for user, :password
  .password.text_field
    = f.label :password_confirmation, t('users.form.confirm_password')
    = f.password_field :password_confirmation, :autocomplete => 'off'
    = errors_for user, :password_confirmation

  - build_user_phone_number(user)
  = f.fields_for :card do |card|
    = card.fields_for :phone_numbers do |phone|
      .phone_number.text_field
        = phone.label :name, t('users.form.phone')
        = phone.text_field :name
        .field_note= t('users.form.phone_for_integration')

app/views/users/form/_notifications.haml
.check_boxes.notifications
  %p= t('.clarification', :login => user.login)
  .check_box.notify
    = f.check_box :notify_conversations
    = f.label :notify_conversations, t('.notify_conversations')
  .check_box.notify
    = f.check_box :notify_tasks
    = f.label :notify_tasks, t('.notify_tasks')
  .check_box.notify
    = f.check_box :notify_pages
    = f.label :notify_pages, t('.notify_pages')

%br
%h3= t('.notification_options')
.watch_new= t('.watch_new_item')
%table.notifications
  %tr.sub-header
    %th.project= t('.project_name')
    %th.digest= t('.digest')
    %th.checkbox= t('.watch_new_task')
    %th.checkbox= t('.watch_new_conversation')
    %th.checkbox= t('.watch_new_page')
  %tr
    %td.project= t('.default')
    %td= f.select :default_digest, digest_select_options
    %td.checkbox= f.check_box :default_watch_new_task
    %td.checkbox= f.check_box :default_watch_new_conversation
    %td.checkbox= f.check_box :default_watch_new_page

  = f.fields_for :people do |person|
    %tr
      %td.project= person.object.project.name
      %td= person.select :digest, digest_select_options
      %td.checkbox= person.check_box :watch_new_task
      %td.checkbox= person.check_box :watch_new_conversation
      %td.checkbox= person.check_box :watch_new_page

.notifications.many_fields
  .notify
    = f.label :digest_delivery_hour, t('.digest_delivery_time')
    = f.select :digest_delivery_hour, (0..24).collect {|i| [ l(Time.now.at_midnight + i.hours, :format => :short), i ] }
  .check_box.notify
    = f.check_box :wants_task_reminder
    = f.label :wants_task_reminder, t('.wants_task_reminder')
  .check_box.notify
    = f.check_box :instant_notification_on_mention
    = f.label :instant_notification_on_mention, t('.notify_on_mention')

app/views/users/form/_picture.haml
%p= t(user.avatar?? '.we_have_this_avatar_html' : '.gravatar_in_use_html', :gravatar => gravatar_url)
%p= t('.upload_here_or_at_gravatar_html', :gravatar => gravatar_url)
%p
  = f.label :avatar, t('.field')
  = f.file_field :avatar
- if user.avatar?
  %p
    = f.label :avatar_destroy, t('.destroy')
    = f.check_box :avatar_destroy

.your_avatars
  = image_tag avatar_or_gravatar(user, :profile)
  = image_tag avatar_or_gravatar(user, :thumb)
  = image_tag avatar_or_gravatar(user, :micro)

app/views/users/form/_profile.haml
.first_name.text_field
  = f.label :first_name, t('users.form.first_name')
  = f.text_field :first_name, :autofocus => 'autofocus'
  = errors_for user, :first_name
.last_name.text_field
  = f.label :last_name, t('users.form.last_name')
  = f.text_field :last_name
  = errors_for user, :last_name

.description.text_area
  = f.label :biography, t('users.form.biography')
  = f.text_area :biography

= list_card_fields(f,%w(phone_numbers email_addresses websites addresses ims social_networks))

app/views/users/form/_settings.haml
.login.text_field
  = f.label :login, t('users.form.login')
  = f.text_field :login
  = errors_for user, :login
.email.text_field
  = f.label :email, t('users.form.email')
  - if (@invitation || @app_link)
    = f.text_field :email, :readonly => 'readonly', :style => 'color: #999'
  - else
    = f.text_field :email
  = errors_for user, :email

#password_fields{ :style => 'display: none' }
  .password.text_field
    = f.label :old_password, t('users.form.old_password')
    = f.password_field :old_password, :autocomplete => 'off'
    = errors_for user, :old_password
  .password.text_field
    = f.label :password, t('users.form.password')
    = f.password_field :password, :autocomplete => 'off'
    = errors_for user, :password
  .password.text_field
    = f.label :password_confirmation, t('users.form.confirm_password')
    = f.password_field :password_confirmation, :autocomplete => 'off'
    = errors_for user, :password_confirmation

#change_password_link
  = link_to_function t('users.form.change_password'), show_user_password_fields

.first_day_of_week.select
  = f.label :first_day_of_week, t('users.form.first_day_of_week')
  = f.select :first_day_of_week, [[t('users.form.sunday'), 'sunday'],[t('users.form.monday'), 'monday']]
    
.language.select
  = f.label :locale, t('users.form.language')
  = f.select :locale, locale_select_values
  
.time_zone.select
  = f.label :time_zone, t('users.form.time_zone')
  = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Eastern Time (US & Canada)"

.autoaccept.check_box
  = f.check_box :auto_accept_invites
  = f.label :auto_accept_invites, t('users.form.auto_accept_invites'), :style => 'float: none'

.betatester.check_box
  = f.check_box :betatester
  = f.label :betatester, t('users.form.betatester'), :style => 'float: none'

.show_badges.check_box
  = f.check_box :show_badges
  = f.label :show_badges, t('users.form.badges'), :style => 'float: none'

.keyboard_shortcuts.check_box
  = f.check_box :keyboard_shortcuts
  = f.label :keyboard_shortcuts, t('users.form.keyboard_shortcuts'), :style => 'float: none'