config/routes.rb
Teambox::Application.routes.draw do

  # If secure_logins is true, constrain matches to ssl requests
  class SSLConstraints
    def self.matches?(request)
      !Teambox.config.secure_logins || request.ssl?
    end
  end

  resources :sites, :only => [:show, :new, :create]

  match '/public' => 'public/projects#index', :as => :public_projects
  match '/goodbye' => 'static_pages#goodbye', :as => :goodbye 

  namespace :public do
    match ':id' => 'projects#show', :as => :project
    match ':project_id/conversations' => 'conversations#index', :as => :project_conversations
    match ':project_id/conversations/:id' => 'conversations#show', :as => :project_conversation
    match ':project_id/:id' => 'pages#show', :as => :project_page
  end

  match 'api' => 'apidocs#index', :as => :api
  match 'api/concepts' => 'apidocs#concepts', :as => :api_concepts
  match 'api/routes' => 'apidocs#routes', :as => :api_routes
  match 'api/auth' => 'apidocs#auth', :as => :api_auth
  match 'api/changes' => 'apidocs#changes', :as => :api_changes
  match 'api/:model' => 'apidocs#model', :as => :api_model

  resources :sprockets, :only => [:index, :show]

  #Constrain all requests to the ssl constraint
  scope :constraints => SSLConstraints do

    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/login/:username' => 'sessions#backdoor', :as => :login_backdoor if Rails.env.cucumber?

    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup

    match '/search' => 'search#index', :as => :search

    match '/guides' => 'guides#index', :as => :guides

    match '/text_styles' => 'users#text_styles', :as => :text_styles
    match '/email_posts_path' => 'users#email_posts', :as => :email_posts
    match '/invite_format' => 'invitations#invite_format', :as => :invite_format
    match '/feeds' => 'users#feeds', :as => :feeds
    match '/calendars' => 'users#calendars', :as => :calendars
    match '/disable_splash' => 'users#disable_splash', :as => :disable_splash
    match '/forgot' => 'reset_passwords#new', :as => :forgot_password
    match '/reset/:reset_code' => 'reset_passwords#reset', :as => :reset_password
    match '/forgetting' => 'reset_passwords#update_after_forgetting', :as => :update_after_forgetting, :method => :put
    match '/reset_password_sent' => 'reset_passwords#sent', :as => :sent_password

    match '/format/:f' => 'sessions#change_format', :as => :change_format

    match '/projects/:project_id/invite/:login' => 'invitations#create', :as => :create_project_invitation, :method => :post

    match '/auth/:provider/callback' => 'auth#callback', :as => :auth_callback
    match '/auth/failure' => 'auth#failure', :as => :auth_failure
    match '/complete_signup' => 'users#complete_signup', :as => :complete_signup
    match '/auth/:provider/unlink' => 'users#unlink_app', :as => :unlink_app

    resources :google_docs do
      get :search, :on => :collection
    end
    
    resources :google_calendars

    #RAILS 3 Useless resource?
    resources :reset_passwords
    resource :session

    resources :organizations do
      member do
        get :projects
        get :external_view
        get :delete
        get :appearance
        put :update_appearance
      end
      resources :memberships do
        member do
          get :change_role
          get :add
          get :remove
        end
      end
      resources :task_list_templates do
        collection do
          put :reorder
        end
      end
    end

    match '/account/settings' => 'users#edit', :as => :account_settings, :sub_action => 'settings'
    match '/account/picture' => 'users#edit', :as => :account_picture, :sub_action => 'picture'
    match '/account/profile' => 'users#edit', :as => :account_profile, :sub_action => 'profile'
    match '/account/linked_accounts' => 'users#edit', :as => :account_linked_accounts, :sub_action => 'linked_accounts'
    match '/account/notifications' => 'users#edit', :as => :account_notifications, :sub_action => 'notifications'
    match '/account/delete' => 'users#edit', :as => :account_delete, :sub_action => 'delete'
    match '/account/destroy' => 'users#destroy', :as => :destroy_user
    match '/account/activity_feed_mode/collapsed' => 'users#change_activities_mode', :as => :collapse_activities, :collapsed => true
    match '/account/activity_feed_mode/expanded' => 'users#change_activities_mode', :as => :expand_activities, :collapsed => false
    match '/account/watch_list' => 'watchers#index', :as => :watch_list
    post  '/account/watch_list/unwatch/:watch_id' => 'watchers#unwatch', :as => :unwatch
    post  '/account/stats/:stat/inc' => 'users#increment_stat'
    post  '/account/badge/:badge/grant' => 'users#grant_badge'
    post  '/account/first_steps/hide' => 'users#hide_first_steps'

    resources :teambox_datas, :path => '/datas' do
      member do
        get :download
      end
    end

    resources :users do
      resources :invitations
      member do
        get :confirm_email
        get :unconfirmed_email
        get :contact_importer
      end
      resources :conversations
      resources :task_lists do
        resources :tasks
      end
      match 'activities/users/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    end

    match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
    match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    match 'activities/:id/show_thread(.:format)' => 'activities#show_thread', :as => :show_thread, :method => :get

    match 'projects/archived.:format' => 'projects#index', :as => :project_archived, :sub_action => 'archived'

    match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

    resources :projects do
      member do
        post :accept
        post :decline
        get :join
      end

      match 'time/:year/:month' => 'hours#index', :as => :hours_by_month, :via => :get
      match 'time/by_period' => 'hours#by_period', :as => :hours_by_period, :via => :get
      match 'time' => 'hours#index', :as => :time
      match 'settings' => 'projects#edit', :as => :settings, :sub_action => 'settings'
      match 'picture' => 'projects#edit', :as => :picture, :sub_action => 'picture'
      match 'deletion' => 'projects#edit', :as => :deletion, :sub_action => 'deletion'
      match 'ownership' => 'projects#edit', :as => :ownership, :sub_action => 'ownership'

      resources :invitations do
        member do
          put :accept
          put :decline
          get :resend
        end
      end

      match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
      match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get

      match 'move/:id' => 'uploads#move', :via => :put, :as => :move_resource

      resources :uploads do
        member do
          get :public_download
          put :rename
        end
        collection do
          resources :folders, :except => [:show, :index, :new] do
            member do
              get :public_download, :controller => 'uploads', :action => 'public_download'
              put :rename
            end
          end
        end
      end

      match 'downloadable/:id/email_public' => "uploads#email_public", :via => :post, :as => :email_public_download
      
      match 'uploads/folders/:id' => 'uploads#index', :via => :get
      match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

      match 'invite_people' => 'projects#invite_people', :as => :invite_people, :via => :get
      match 'invite_people' => 'projects#send_invites', :as => :send_invites, :via => :post

      resources :tasks do
        member do
          put :reorder
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :task_lists do
        collection do
          get :gantt_view
          get :archived
          put :reorder
        end
        member do
          put :archive
          put :unarchive
          put :watch
          put :unwatch
        end

        resources :tasks do
          member do
            put :watch
            put :unwatch
          end

          resources :comments
        end
      end

      match 'contacts' => 'people#contacts', :as => :contacts, :method => :get

      resources :people do
        member do
          get :destroy
        end
      end

      resources :conversations do
        member do
          put :convert_to_task
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :pages do
        collection do
          post :resort
        end
        member do
          post :reorder
          put :watch
          put :unwatch
        end
        # In rails 2, we have :pages, :has_many => :task_list ?!
        resources :notes,:dividers,:uploads
      end

      match 'search' => 'search#index', :as => :search

      resources :google_docs do
        collection do
          :search
        end
        member do
          put :write_access, :path => "write_access/:access", :access => /lock|unlock/
        end
      end
    end

    namespace :api_v1, :path => 'api/1' do
      resources :app_links, :except => [ :edit, :update ]
      resources :projects, :except => [:new, :edit] do

        resources :activities, :only => [:index, :show]

        resources :people, :except => [:create, :new, :edit]

        resources :comments, :except => [:new, :create, :edit]

        resources :conversations, :except => [:new, :edit] do
          member do
            put :watch
            put :unwatch
            post :convert_to_task
          end

          resources :comments, :except => [:new, :edit]
        end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]
  skip_before_filter :load_project

  def index
    @tokens = current_user.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
  end
  
  def developer
    @client_applications = current_user.client_applications
  end

  def new
    @client_application = ClientApplication.new
  end

  def create
    @client_application = current_user.client_applications.build(params[:client_application])
    if @client_application.save
      flash[:notice] = "Registered the information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @client_application.update_attributes(params[:client_application])
      flash[:notice] = "Updated the client information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "edit"
    end
  end

  def destroy
    @client_application.destroy
    flash[:notice] = "Destroyed the client application registration"
    redirect_to :action => "index"
  end

  private
  
  def get_client_application
    unless @client_application = current_user.client_applications.find(params[:id])
      flash.now[:error] = "Wrong application id"
      redirect_to oauth_clients_path
    end
  end
end

app/helpers/oauth_clients_helper.rb
module OauthClientsHelper
  def new_oauth_client_link
    link_to content_tag(:span,t('oauth_clients.index.register_app')), new_oauth_client_path, :class => 'add_button'
  end
end

app/views/oauth_clients/_client.haml
.oauth_client[client]
  .name
    %h2= link_to client.name, oauth_client_path(client.id)
  .actions
    = link_to t('.edit'), edit_oauth_client_path(client)

app/views/oauth_clients/_client_token.haml
.client_token[client_token]
  .name
    %h2= link_to client_token.client_application.name, client_token.client_application.url
    %p= t('.authorized_at', :time => client_token.authorized_at.to_s)
  .actions
    = link_to t('.revoke'), revoke_path(:token => client_token.token), 
      'data-confirm' => t('.confirm_revoke'), 'data-method' => 'post', 'data-remote' => true,
      :class => 'revoke'

app/views/oauth_clients/_form.haml
=error_messages_for :client_application
.text_field
  = f.label :name, t('.name')
  = f.text_field :name

.text_field
  = f.label :url, t('.url')
  = f.text_field :url

.text_field
  = f.label :callback_url, t('.callback_url')
  = f.text_field :callback_url

.text_field
  = f.label :support_url, t('.support_url')
  = f.text_field :support_url

app/views/oauth_clients/developer.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')

= new_oauth_client_link

- if @client_applications.empty?
  %p= t('.no_registered_applications_html')
- else
  %p= t('.registered_applications_html')
  #oauth_clients
    = render :partial => 'client', :collection => @client_applications

app/views/oauth_clients/edit.haml
- content_for :column do
  = render 'shared/user_navigation'

.oauth_client_header
  .text_actions
    = link_to t('common.delete'), oauth_client_path(@client_application),
      'data-confirm' => t('oauth_clients.edit.confirm_delete'), 'data-method' => 'delete'
  %h2
    = @client_application.name

- form_for :client_application, :url => oauth_client_path(@client_application), :html => {:method => 'put', :id => 'edit_oauth_clients'} do |f|
  = render :partial => "form", :locals => { :f => f }
  = submit_tag t('.submit')
  = t('common.or')
  = link_to t('common.cancel'), oauth_client_path(@client_application)

app/views/oauth_clients/index.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')
- unless @tokens.empty?
  %p= t('.authorized_applications')

  #client_tokens
    = render :partial => 'client_token', :collection => @tokens
- else
  %p= t('.no_authorized_applications')

%p
  = t('.developers_register_html', :url => developer_oauth_clients_path)

app/views/oauth_clients/new.haml
- content_for :column do
  = render 'shared/user_navigation'

%h2= t('.title')

- form_for :client_application, :url => { :action => :create }, :html => {:id => 'new_oauth_clients'} do |f|
  = render :partial => "form", :locals => { :f => f }
  = submit_tag t('.submit')
  = t('common.or')
  = link_to t('common.cancel'), developer_oauth_clients_path

app/views/oauth_clients/show.haml
- content_for :column do
  = render 'shared/user_navigation'

.oauth_client_header
  .text_actions
    = link_to 'Edit', edit_oauth_client_path(@client_application)
    = t('common.or')
    = link_to 'Back', developer_oauth_clients_path
  %h2
    = @client_application.name

%h3 App Key
%pre=@client_application.key

%h3 App Secret
%pre=@client_application.secret

%h3 Callback URI
%pre=@client_application.callback_url

%h3 Access Token URL
%pre
  ="http#{'s' if request.ssl?}://#{request.host_with_port}#{token_path}"

%h3 Authorize URL
%pre
  ="http#{'s' if request.ssl?}://#{request.host_with_port}#{authorize_path}"

%p
  For more details, please
  = link_to 'read the Authentication section in the API Docs', api_auth_path